on:
  push:
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        sbt: ["1.11.5", "2.0.0-RC4"]
        os: [ubuntu-latest, macos-latest]
        java: [11, 17, 21]
    runs-on: "${{ matrix.os }}"
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: "${{ matrix.java }}"
    - uses: sbt/setup-sbt@v1
    - run: mkdir project
    - run: echo "sbt.version=${{ matrix.sbt }}" > project/build.properties
    - run: sbt test
